project:
  type: website

website:
  title: Data Science 2023 #IfG Data Processsing Center
  navbar:
    background: secondary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Program"
        file: program.qmd
      - text: "Venue"
        file: venue.qmd
      - text: "Announcement"
        file: annnouncement.qmd  

format:
  html:
    theme: minty
    css: styles.css
    toc: true