---
title: 'Kadi4Mat ELN'
---

Philosophy/idea/necessity/FAIR
bottleneck

Kadi4Mat – or in short *Kadi* – is an Electronic Lab Notebook (ELN) that we use for EPMA results management and making data FAIR. Kadi is an online system that can be accessed with only a browser. A login is might be possible through your university email (if the Shibboleth AAI is connected to Kadi) or by applying for an account. However, we use the Kadi Python API for our tools, and with these, no login to Kadi is necessary.


# Definitions & Naming Conventions
## Campaign
A measurement sessions We call a measurement session What is a campaign, i.e., what files are part of a campaign?

What if one campaign uses different measurement parameters/programs?

store everything in one place

Each campaign becomes a sensible name, that is then also the record name on Kadi.
On Kadi, things are called 'record'.

## Kadi record PID naming
E.g.: guf-ifg-epma-NAME-NUMBER\
or:  guf-ifg-epma-NUMBER-NAME\
This should be documented together with the Kadi PID in an Excel file? Or could that be retrieved automatically?

A campaign is the same as a record, i.e., it beocmes a record once it is uploaded to Kadi

## Subsequent Naming
A number of files need to be produced and/or uploaded to Kadi. The file names in italic are mandator names, that need to be used exactly as given when these are uploaded to Kadi. The data processing web-interface requires exactly these names to work properly.

## Work-Flow Block Chart
xxx


# Prepare Files
After each measurement campaign, create a folder with the campaign name. This should be the same name used for the Kadi record.

## Quantitative Data
the 4 following files need to be produced:

**1. Full Summary (csv)**\
If multiple files
Include standards

**2. Standard Summary (txt)**\
summary -> standard(?)

**3. Standard Normal (txt)**\
xxx

**4. Measurement Conditions (txt)**\
Save the measurement file, so it appears in 'Quick'. In Quick,right-click the measurement file, click on *confirm*, and save the text file with the name *measurement conditions.txt*.


## Flank Method Data
The same as in *Quantitative Data*, plus an offline corrected full summary file (csv).


## Electron Images
xx


## Element Maps
xx


## Additional Files
Processed data, e.g., BSE images with points on these.



# Upload
Upload all files to [Kadi4Mat](https://kadi4mat.iam-cms.kit.edu/login).

Provide additional, sensible info. Inivite the person to the respective group. Include the Kadi record in other, sensible groups.



# Produce a Results File
xx


# Post-Processing Data
xx